version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
      - ./frontend/static:/app/static

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - ./frontend/static:/app/static
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - FASTAPI_HOST=0.0.0.0
    volumes:
      - ./backend:/code

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apteka
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  node-modules:
  db-data: