services:
  proxy:
    image: nginx:mainline
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      # - ./frontend/static:/app/static
      - static_files:/usr/share/nginx/html/static/
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
      # - ./frontend/static:/app/static
      - static_files:/app/build/
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - FASTAPI_HOST=0.0.0.0
      - STATIC_FILES_PATH=/shared_files/
    volumes:
      - ./backend:/code
      - static_files:/shared_files
    networks:
      - app-network

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apteka
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  node-modules:
  db-data:
  static_files:

networks:
  app-network:
    driver: bridge