version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules

  backend:
    build: ./backend
    ports:
      - "80:80"
    environment:
      - FASTAPI_HOST=0.0.0.0
    volumes:
      - ./backend:/code
      - ./frontend/src/img:/app/frontend/src/img

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apteka
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  node-modules:
  db-data: